<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="studyProgramStructure" nsURI="http://tdt4250/modelingExercise/studyProgramStructure"
    nsPrefix="tdt4250.modelingExercise.studyProgramStructure">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroups" eType="#//CourseGroup"
        eOpposite="#//CourseGroup/courses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfSemesters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degree" eType="#//degree"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialisations" upperBound="-1"
        eType="#//Specialization" containment="true" eOpposite="#//Specialization/program"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" eType="#//Semester"
        containment="true" eOpposite="#//Semester/program"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialization">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfSemesters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" eType="#//Semester"
        containment="true" eOpposite="#//Semester/specialisation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" eType="#//Program"
        eOpposite="#//Program/specialisations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Specializations" eType="#//Specialization"
        containment="true" eOpposite="#//Specialization/Specialization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Specialization" eType="#//Specialization"
        eOpposite="#//Specialization/Specializations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="creditsShouldBe30"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="season" eType="#//season"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroups" upperBound="-1"
        eType="#//CourseGroup" containment="true" eOpposite="#//CourseGroup/semester"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" eType="#//Program"
        eOpposite="#//Program/semesters"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialisation" eType="#//Specialization"
        eOpposite="#//Specialization/semesters"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="neededCredits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseGroup">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="courseFromLevel"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="courseFromLevel" value="if self.levelRestriction != null then self.courses.course.level==self.levelRestriction else endif"/>
      <details key="courseFromField" value="if self.field != null and self.fromField != null then if self.fromField then self.courses.course.code.startWith(self.field) else !self.courses.course.code.startWith(self.field) endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfNeededCourses" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semester" eType="#//Semester"
        eOpposite="#//Semester/courseGroups"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="levelRestriction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="field" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" eOpposite="#//Course/courseGroups"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//courseStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StudyPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programs" eType="#//Program"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" eType="#//Course"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="degree">
    <eLiterals name="bachelor"/>
    <eLiterals name="master" value="1"/>
    <eLiterals name="integratedMaster" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="season">
    <eLiterals name="fall"/>
    <eLiterals name="spring" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="courseStatus">
    <eLiterals name="mandatory"/>
    <eLiterals name="elective" value="1"/>
  </eClassifiers>
</ecore:EPackage>
